
name: Test Backend and Preview Frontend
on: 
  push:
    branches-ignore:
      - main
      - dev
jobs:

  backend_tests:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make environment
        run: make environment

      - name: Install requirements
        run: make requirements

      - name: Run format
        run: make format-check

      - name: Run security checks
        run: make security

      - name: Run tests
        run: make run-tests
        env:
          FIREBASE_SERVICE_ACCOUNT_SIMPLE_SHOPPING_GCP: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIMPLE_SHOPPING_GCP }}

  build_and_preview:
    runs-on: ubuntu-latest
    needs: backend_tests
    
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React App
        working-directory: ./frontend
        run: npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Deploy to Firebase Dev
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIMPLE_SHOPPING_GCP }}
          channelId: dev
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        