
name: Deploy to Firebase Live
on:
  push:
    branches:
      - main
jobs:

  backend_tests:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make environment
        run: make environment

      - name: Install requirements
        run: make requirements

      - name: Run format
        run: make format-check

      - name: Run security checks
        run: make security

      - name: Run tests
        run: make run-tests

  deploy_cloud_run:
    runs-on: ubuntu-latest
    needs: backend-tests

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v0
        with: 
          credentials_json: '{{ secrets.SA_CREDS }}'


  build_and_deploy:
    runs-on: ubuntu-latest
    needs: deploy_cloud_run

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build React App
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Firebase Live
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIMPLE_SHOPPING_GCP }}
          channelId: live
          projectId: simple-shopping-gcp
