
name: Deploy to Firebase Live
on:
  push:
    branches:
      - main

jobs:


  deploy_cloud_run:
    runs-on: ubuntu-latest
    needs: backend_tests

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v2
        with: 
          credentials_json: ${{ secrets.SA_CREDS }}

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'shopping-list-fastapi'
          region: 'europe-west2'
          source: './backend'
      
      - name: Debug Info
        run: gcloud run services describe shopping-list-fastapi --region europe-west2


