name: Main CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v4

      - name: Test echo
        run : echo "This is dev"
