name: Deploy with Terraform

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud CLI
        uses: google-github-actions/auth@v2
        with: ${{ secrets.DEV_KEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: simple-shopping-dev

      - name: Authenticate with Google Cloud (Development)
        run: |
          echo "${{ secrets.DEV_KEY }}" | gcloud auth activate-service-account --key-file=-

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
