
name: Deploy to Firebase Dev
on: 
  push:
    branches:
      - dev
jobs:

  backend_tests:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Make environment
        run: make environment

      - name: Install requirements
        run: make requirements

      - name: Run format
        run: make format-check

      - name: Run security checks
        run: make security

      - name: Run tests
        run: make run-tests


  build_and_preview:
    runs-on: ubuntu-latest
    needs: backend_tests
    
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install Bootstrap
        run: npm i bootstrap && npm i reactstrap react react-dom

      - name: Build React App
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Firebase Dev
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIMPLE_SHOPPING_GCP }}
          channelId: dev
          projectId: simple-shopping-gcp
