name: Deploy React

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        run: echo "This is dev"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      